def create(address: int, width: int, batch: int, mapping: list[tuple[int, int, int]]) -> object: ...
def push(state: object, model: int) -> bytes | None: ...
def flush(state: object) -> bytes | None: ...

def solve(state: object, control: int, addresses: tuple[int, ...], consume: object, measure: bool) -> tuple[int, float]: ...

def prepare_decode(width: int, slots: tuple, literal: object, clause: object) -> object: ...

def decode_block(plan: object, block: bytes) -> list: ...

def prepare_renderer(build: int, string: int, size: int, release: int, rule_type: int) -> object: ...

def render_rules(renderer: object, parts: tuple[tuple[int, tuple[int, ...]], ...]) -> tuple[str, ...]: ...
